version: "3.9"

services:
  db:
    image: postgres:15
    container_name: API_Power_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: API_POWER_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    command: python app.py

volumes:
  pgdata: